package com.example.sino.db.entity.form;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Entity mapped to table "FORM_QUESTION_GROUP_FORM".
 */

@Entity(tableName = "FormQuestionGroupForm")
public class FormQuestionGroupForm {
    @PrimaryKey(autoGenerate = true)
    private Long id;
    private String groupName;
    private long formId;
    private long formQuestionGroupId;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public long getFormId() {
        return formId;
    }

    public void setFormId(long formId) {
        this.formId = formId;
    }

    public long getFormQuestionGroupId() {
        return formQuestionGroupId;
    }

    public void setFormQuestionGroupId(long formQuestionGroupId) {
        this.formQuestionGroupId = formQuestionGroupId;
    }
}
